project:
  type: website
  post-render: ./clean-datasets.sh

website:
  title: "DataLad Tutorial for EuroScipy 25"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Exercises
        menu:
          - text: "Part 1: Working with Datasets"
            href: notebooks/exercises1.qmd
          - text: "Part 2: Tracking Changes"
            href: notebooks/exercises2.qmd
          - text: "Part 3: Distributing your Dataset"
            href: notebooks/exercises3.qmd
      - text: Slides
        menu:
          - text: Introduction
            href: slides/intro.qmd
          - text: Exercise Review 1
            href: notebooks/review1.qmd
          - text: Exercise Review 2
            href: notebooks/review2.qmd

format:
  html:
    theme:
      - cosmo
      - brand



