[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "DataLad-EuroScipy25"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
quarto_preview = "quarto preview --no-browser"
quarto_render = "quarto render"
quarto_publish = "quarto publish"

[tasks.preview]
depends-on = [
  { task = "quarto_preview", environment = "render" },
]

[tasks.publish]
depends-on = [
  { task = "quarto_render", environment = "render" },
  { task = "quarto_publish" },
]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
git-annex = ">=10.20250721, <11"
datalad = ">=1.2.1, <2"
pandas = ">=2.3.1, <3"
datalad-next = ">=1.5.0, <2"

[feature.render.pypi-dependencies]
bash-kernel = ">=0.10.0, <0.11"
jupyter = ">=1.1.1, <2"

[environments]
render = ["render"]



