---
title: "Ole Bialas"
format: html
---

I studied Biology at the University of Tübingen, where I first learned how to code using Matlab. 
Then, I moved to Leipzig, where I did a master’s degree and later a PhD in neurobiology. 
In my research, I studied how the brain processes sound location using electroencephalography (EEG) and custom experimental setups for spatial audio. 
During that time, I started using Python and eventually co-authored [slab](https://slab.readthedocs.io/en/latest/), a Python toolbox for psychoacoustic experiments. 
After my PhD, I moved to the University of Rochester in New York, where I studied how the brain processes naturalistic speech by modeling EEG that was recorded while the participants listened to audiobooks. 
For this research I published another toolbox, originally written in Matlab, called [mTRFpy](https://mtrfpy.readthedocs.io/en/latest/). 
As my postdoc was coming to an end, I was looking for a position where I could combine my interest in neuroscience with my passion for programming. 
I found such a position at the iBehave Open Technology Support [iBOTS](https://ibehave.nrw/people/ibots-team/) where I currently work as a research software consultant. 
In this position, I develop and teach workshops where neuroscience researchers can improve their software skills and I do one-on-one consulting to help neuroscientists deal with the computational challenges they are faced in their research.
